### PR TITLE
webdav endpoint v1 BasicAuthentication

### LINKED ISSUE #149: OAuth2 password flow support for `/remote.php/webdav` endpoint
#128 and #136 were about OAuth2 password flow for webdav authentication, in order to support *DAV clients that cannot handle token authentication.

Some clients like [GNOME Online Accounts](https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/67) still authenticate against the `/remote.php/webdav` endpoint. Currently basic authentication with nextcloud-oidc-login does not work on this endpoint.

### PR DESCRIPTION
**Pull request by azmeuk**
This allows clients that still use the `/remote.php/webdav` endpoint, such as [GNOME Online Accounts](https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues/67) to authenticate against a OIDC identity provider with user and password.

It registers the `BasicAuthBackend` on the `addPlugin` event [raised in v1/webdav.php](
https://github.com/nextcloud/server/blob/a353db2c316773d680f8cfedf036c2b9bc54c16e/apps/dav/appinfo/v1/webdav.php#L80).

Then it avoids to execute session related operations, due to the session always being closed in this situation. I [detailed this issue on the nextcloud/server bugtracker](https://github.com/nextcloud/server/issues/31091), but to summarize, the default authentication backend plugged in the `remote.php/webdav` endpoint always closes the session before our backend can do anything.

Due to that issue, the logs are full of [`login failed` warnings](https://github.com/nextcloud/server/blob/f9fb5f50dd1e4db8a81ad935c29f3490d1f9fa79/lib/private/User/Manager.php#L232) raised by the default authentication backend, even if the authentication by our backend succeeds in the end.

I would love to hear your thoughts on this @sirkrypt0, as I am not sure how bad the `if (PHP_SESSION_ACTIVE === session_status())` parts are, and if you can think of another way to do.

This patch depends on #159 and fixes #149.

### CODE REVIEW

File: lib/WebDAV/BasicAuthBackend.php [hunk 1]
```diff
@@ -125,9 +134,19 @@ private function login(string $username, string $password)
 
         list($user, $userPassword) = $this->loginService->login($profile);
 
+        if (PHP_SESSION_ACTIVE === session_status()) {
```
Comment (sirkrypt0) [inline lib/WebDAV/BasicAuthBackend.php:137]: Please add a comment here (and ideally in the `setupUserFs` function above as well) for why this check is necessary. You might also add the link to the Nextcloud issue that requires this workaround.

**Review by sirkrypt0 — CHANGES_REQUESTED** [review]
I'm not a huge fan of the `PHP_SESSION_ACTIVE` parts, but am not fully convinced of the alternatives yet.

I thought about whether adding a user backend is an option here (as [the UserManager uses those to check the password](https://github.com/nextcloud/server/blob/f9fb5f50dd1e4db8a81ad935c29f3490d1f9fa79/lib/private/User/Manager.php#L246-L263)). However, I think it is overkill, especially since this is only a workaround. Furthermore, I'm unsure whether the user backend would be capable of identifying this special case with the `v1` DAV route here.

Alternatively, an explicit check for the `v1` DAV route may be better. It would align the check more with the issue it is caused by (the probably improper default backend implementation for `v1`). What do you think about that alternative?

**Review by sirkrypt0 — APPROVED** [review]
